// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Ivaldi.FlatBuffers.CharacterExcel
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CharacterExcelTable : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static CharacterExcelTable GetRootAsCharacterExcelTable(ByteBuffer _bb) { return GetRootAsCharacterExcelTable(_bb, new CharacterExcelTable()); }
  public static CharacterExcelTable GetRootAsCharacterExcelTable(ByteBuffer _bb, CharacterExcelTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyCharacterExcelTable(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, CharacterExcelTableVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CharacterExcelTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Ivaldi.FlatBuffers.CharacterExcel.CharacterExcel? DataList(int j) { int o = __p.__offset(4); return o != 0 ? (Ivaldi.FlatBuffers.CharacterExcel.CharacterExcel?)(new Ivaldi.FlatBuffers.CharacterExcel.CharacterExcel()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DataListLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Ivaldi.FlatBuffers.CharacterExcel.CharacterExcelTable> CreateCharacterExcelTable(FlatBufferBuilder builder,
      VectorOffset DataListOffset = default(VectorOffset)) {
    builder.StartTable(1);
    CharacterExcelTable.AddDataList(builder, DataListOffset);
    return CharacterExcelTable.EndCharacterExcelTable(builder);
  }

  public static void StartCharacterExcelTable(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDataList(FlatBufferBuilder builder, VectorOffset dataListOffset) { builder.AddOffset(0, dataListOffset.Value, 0); }
  public static VectorOffset CreateDataListVector(FlatBufferBuilder builder, Offset<Ivaldi.FlatBuffers.CharacterExcel.CharacterExcel>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDataListVectorBlock(FlatBufferBuilder builder, Offset<Ivaldi.FlatBuffers.CharacterExcel.CharacterExcel>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataListVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Ivaldi.FlatBuffers.CharacterExcel.CharacterExcel>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataListVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Ivaldi.FlatBuffers.CharacterExcel.CharacterExcel>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDataListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Ivaldi.FlatBuffers.CharacterExcel.CharacterExcelTable> EndCharacterExcelTable(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Ivaldi.FlatBuffers.CharacterExcel.CharacterExcelTable>(o);
  }
  public static void FinishCharacterExcelTableBuffer(FlatBufferBuilder builder, Offset<Ivaldi.FlatBuffers.CharacterExcel.CharacterExcelTable> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedCharacterExcelTableBuffer(FlatBufferBuilder builder, Offset<Ivaldi.FlatBuffers.CharacterExcel.CharacterExcelTable> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class CharacterExcelTableVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*DataList*/, Ivaldi.FlatBuffers.CharacterExcel.CharacterExcelVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
