// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Ivaldi.FlatBuffers.CharacterExcel
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CharacterExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static CharacterExcel GetRootAsCharacterExcel(ByteBuffer _bb) { return GetRootAsCharacterExcel(_bb, new CharacterExcel()); }
  public static CharacterExcel GetRootAsCharacterExcel(ByteBuffer _bb, CharacterExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CharacterExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string DevName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDevNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetDevNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetDevNameArray() { return __p.__vector_as_array<byte>(6); }
  public long CostumeGroupId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public bool IsPlayable { get { int o = __p.__offset(10); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public Ivaldi.FlatBuffers.Common.ProductionStep ProductionStep { get { int o = __p.__offset(12); return o != 0 ? (Ivaldi.FlatBuffers.Common.ProductionStep)__p.bb.GetInt(o + __p.bb_pos) : Ivaldi.FlatBuffers.Common.ProductionStep.ToDo; } }
  public bool CollectionVisible { get { int o = __p.__offset(14); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string ReleaseDate { get { int o = __p.__offset(16); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetReleaseDateBytes() { return __p.__vector_as_span<byte>(16, 1); }
#else
  public ArraySegment<byte>? GetReleaseDateBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public byte[] GetReleaseDateArray() { return __p.__vector_as_array<byte>(16); }
  public string CollectionVisibleStartDate { get { int o = __p.__offset(18); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCollectionVisibleStartDateBytes() { return __p.__vector_as_span<byte>(18, 1); }
#else
  public ArraySegment<byte>? GetCollectionVisibleStartDateBytes() { return __p.__vector_as_arraysegment(18); }
#endif
  public byte[] GetCollectionVisibleStartDateArray() { return __p.__vector_as_array<byte>(18); }
  public string CollectionVisibleEndDate { get { int o = __p.__offset(20); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCollectionVisibleEndDateBytes() { return __p.__vector_as_span<byte>(20, 1); }
#else
  public ArraySegment<byte>? GetCollectionVisibleEndDateBytes() { return __p.__vector_as_arraysegment(20); }
#endif
  public byte[] GetCollectionVisibleEndDateArray() { return __p.__vector_as_array<byte>(20); }
  public bool IsPlayableCharacter { get { int o = __p.__offset(22); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public uint LocalizeEtcId { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public Ivaldi.FlatBuffers.CharacterExcel.Rarity Rarity { get { int o = __p.__offset(26); return o != 0 ? (Ivaldi.FlatBuffers.CharacterExcel.Rarity)__p.bb.GetInt(o + __p.bb_pos) : Ivaldi.FlatBuffers.CharacterExcel.Rarity.N; } }
  public bool IsNPC { get { int o = __p.__offset(28); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public Ivaldi.FlatBuffers.CharacterExcel.TacticEntityType TacticEntityType { get { int o = __p.__offset(30); return o != 0 ? (Ivaldi.FlatBuffers.CharacterExcel.TacticEntityType)__p.bb.GetInt(o + __p.bb_pos) : Ivaldi.FlatBuffers.CharacterExcel.TacticEntityType.None; } }
  public bool CanSurvive { get { int o = __p.__offset(32); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool IsDummy { get { int o = __p.__offset(34); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public int SubPartsCount { get { int o = __p.__offset(36); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public Ivaldi.FlatBuffers.CharacterExcel.TacticRole TacticRole { get { int o = __p.__offset(38); return o != 0 ? (Ivaldi.FlatBuffers.CharacterExcel.TacticRole)__p.bb.GetInt(o + __p.bb_pos) : Ivaldi.FlatBuffers.CharacterExcel.TacticRole.None; } }
  public Ivaldi.FlatBuffers.CharacterExcel.WeaponType WeaponType { get { int o = __p.__offset(40); return o != 0 ? (Ivaldi.FlatBuffers.CharacterExcel.WeaponType)__p.bb.GetInt(o + __p.bb_pos) : Ivaldi.FlatBuffers.CharacterExcel.WeaponType.None; } }
  public Ivaldi.FlatBuffers.CharacterExcel.TacticRange TacticRange { get { int o = __p.__offset(42); return o != 0 ? (Ivaldi.FlatBuffers.CharacterExcel.TacticRange)__p.bb.GetInt(o + __p.bb_pos) : Ivaldi.FlatBuffers.CharacterExcel.TacticRange.Back; } }
  public Ivaldi.FlatBuffers.CharacterExcel.BulletType BulletType { get { int o = __p.__offset(44); return o != 0 ? (Ivaldi.FlatBuffers.CharacterExcel.BulletType)__p.bb.GetInt(o + __p.bb_pos) : Ivaldi.FlatBuffers.CharacterExcel.BulletType.Normal; } }
  public Ivaldi.FlatBuffers.CharacterExcel.ArmorType ArmorType { get { int o = __p.__offset(46); return o != 0 ? (Ivaldi.FlatBuffers.CharacterExcel.ArmorType)__p.bb.GetInt(o + __p.bb_pos) : Ivaldi.FlatBuffers.CharacterExcel.ArmorType.LightArmor; } }
  public Ivaldi.FlatBuffers.CharacterExcel.AimIKType AimIKType { get { int o = __p.__offset(48); return o != 0 ? (Ivaldi.FlatBuffers.CharacterExcel.AimIKType)__p.bb.GetInt(o + __p.bb_pos) : Ivaldi.FlatBuffers.CharacterExcel.AimIKType.None; } }
  public Ivaldi.FlatBuffers.CharacterExcel.School School { get { int o = __p.__offset(50); return o != 0 ? (Ivaldi.FlatBuffers.CharacterExcel.School)__p.bb.GetInt(o + __p.bb_pos) : Ivaldi.FlatBuffers.CharacterExcel.School.None; } }
  public Ivaldi.FlatBuffers.CharacterExcel.Club Club { get { int o = __p.__offset(52); return o != 0 ? (Ivaldi.FlatBuffers.CharacterExcel.Club)__p.bb.GetInt(o + __p.bb_pos) : Ivaldi.FlatBuffers.CharacterExcel.Club.None; } }
  public int DefaultStarGrade { get { int o = __p.__offset(54); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MaxStarGrade { get { int o = __p.__offset(56); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public Ivaldi.FlatBuffers.CharacterExcel.StatLevelUpType StatLevelUpType { get { int o = __p.__offset(58); return o != 0 ? (Ivaldi.FlatBuffers.CharacterExcel.StatLevelUpType)__p.bb.GetInt(o + __p.bb_pos) : Ivaldi.FlatBuffers.CharacterExcel.StatLevelUpType.Standard; } }
  public Ivaldi.FlatBuffers.CharacterExcel.SquadType SquadType { get { int o = __p.__offset(60); return o != 0 ? (Ivaldi.FlatBuffers.CharacterExcel.SquadType)__p.bb.GetInt(o + __p.bb_pos) : Ivaldi.FlatBuffers.CharacterExcel.SquadType.None; } }
  public bool Jumpable { get { int o = __p.__offset(62); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public long PersonalityId { get { int o = __p.__offset(64); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long CharacterAIId { get { int o = __p.__offset(66); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long ExternalBTId { get { int o = __p.__offset(68); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long MainCombatStyleId { get { int o = __p.__offset(70); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int CombatStyleIndex { get { int o = __p.__offset(72); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string ScenarioCharacter { get { int o = __p.__offset(74); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetScenarioCharacterBytes() { return __p.__vector_as_span<byte>(74, 1); }
#else
  public ArraySegment<byte>? GetScenarioCharacterBytes() { return __p.__vector_as_arraysegment(74); }
#endif
  public byte[] GetScenarioCharacterArray() { return __p.__vector_as_array<byte>(74); }
  public uint SpawnTemplateId { get { int o = __p.__offset(76); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public int FavorLevelupType { get { int o = __p.__offset(78); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int EquipmentSlotLength { get { int o = __p.__offset(80); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public uint WeaponLocalizeId { get { int o = __p.__offset(82); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public bool DisplayEnemyInfo { get { int o = __p.__offset(84); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public long BodyRadius { get { int o = __p.__offset(86); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long RandomEffectRadius { get { int o = __p.__offset(88); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public bool HPBarHide { get { int o = __p.__offset(90); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public float HpBarHeight { get { int o = __p.__offset(92); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float HighlightFloaterHeight { get { int o = __p.__offset(94); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float EmojiOffsetX { get { int o = __p.__offset(96); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float EmojiOffsetY { get { int o = __p.__offset(98); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int MoveStartFrame { get { int o = __p.__offset(100); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MoveEndFrame { get { int o = __p.__offset(102); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int JumpMotionFrame { get { int o = __p.__offset(104); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int AppearFrame { get { int o = __p.__offset(106); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool CanMove { get { int o = __p.__offset(108); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool CanFix { get { int o = __p.__offset(110); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool CanCrowdControl { get { int o = __p.__offset(112); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool CanBattleItemMove { get { int o = __p.__offset(114); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool IsAirUnit { get { int o = __p.__offset(116); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public long AirUnitHeight { get { int o = __p.__offset(118); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int TagsLength { get { int o = __p.__offset(120); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public long SecretStoneItemId { get { int o = __p.__offset(122); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int SecretStoneItemAmount { get { int o = __p.__offset(124); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public long CharacterPieceItemId { get { int o = __p.__offset(126); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int CharacterPieceItemAmount { get { int o = __p.__offset(128); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public long CombineRecipeId { get { int o = __p.__offset(130); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<Ivaldi.FlatBuffers.CharacterExcel.CharacterExcel> CreateCharacterExcel(FlatBufferBuilder builder,
      long Id = 0,
      StringOffset DevNameOffset = default(StringOffset),
      long CostumeGroupId = 0,
      bool IsPlayable = false,
      Ivaldi.FlatBuffers.Common.ProductionStep ProductionStep = Ivaldi.FlatBuffers.Common.ProductionStep.ToDo,
      bool CollectionVisible = false,
      StringOffset ReleaseDateOffset = default(StringOffset),
      StringOffset CollectionVisibleStartDateOffset = default(StringOffset),
      StringOffset CollectionVisibleEndDateOffset = default(StringOffset),
      bool IsPlayableCharacter = false,
      uint LocalizeEtcId = 0,
      Ivaldi.FlatBuffers.CharacterExcel.Rarity Rarity = Ivaldi.FlatBuffers.CharacterExcel.Rarity.N,
      bool IsNPC = false,
      Ivaldi.FlatBuffers.CharacterExcel.TacticEntityType TacticEntityType = Ivaldi.FlatBuffers.CharacterExcel.TacticEntityType.None,
      bool CanSurvive = false,
      bool IsDummy = false,
      int SubPartsCount = 0,
      Ivaldi.FlatBuffers.CharacterExcel.TacticRole TacticRole = Ivaldi.FlatBuffers.CharacterExcel.TacticRole.None,
      Ivaldi.FlatBuffers.CharacterExcel.WeaponType WeaponType = Ivaldi.FlatBuffers.CharacterExcel.WeaponType.None,
      Ivaldi.FlatBuffers.CharacterExcel.TacticRange TacticRange = Ivaldi.FlatBuffers.CharacterExcel.TacticRange.Back,
      Ivaldi.FlatBuffers.CharacterExcel.BulletType BulletType = Ivaldi.FlatBuffers.CharacterExcel.BulletType.Normal,
      Ivaldi.FlatBuffers.CharacterExcel.ArmorType ArmorType = Ivaldi.FlatBuffers.CharacterExcel.ArmorType.LightArmor,
      Ivaldi.FlatBuffers.CharacterExcel.AimIKType AimIKType = Ivaldi.FlatBuffers.CharacterExcel.AimIKType.None,
      Ivaldi.FlatBuffers.CharacterExcel.School School = Ivaldi.FlatBuffers.CharacterExcel.School.None,
      Ivaldi.FlatBuffers.CharacterExcel.Club Club = Ivaldi.FlatBuffers.CharacterExcel.Club.None,
      int DefaultStarGrade = 0,
      int MaxStarGrade = 0,
      Ivaldi.FlatBuffers.CharacterExcel.StatLevelUpType StatLevelUpType = Ivaldi.FlatBuffers.CharacterExcel.StatLevelUpType.Standard,
      Ivaldi.FlatBuffers.CharacterExcel.SquadType SquadType = Ivaldi.FlatBuffers.CharacterExcel.SquadType.None,
      bool Jumpable = false,
      long PersonalityId = 0,
      long CharacterAIId = 0,
      long ExternalBTId = 0,
      long MainCombatStyleId = 0,
      int CombatStyleIndex = 0,
      StringOffset ScenarioCharacterOffset = default(StringOffset),
      uint SpawnTemplateId = 0,
      int FavorLevelupType = 0,
      int EquipmentSlotLength = 0,
      uint WeaponLocalizeId = 0,
      bool DisplayEnemyInfo = false,
      long BodyRadius = 0,
      long RandomEffectRadius = 0,
      bool HPBarHide = false,
      float HpBarHeight = 0.0f,
      float HighlightFloaterHeight = 0.0f,
      float EmojiOffsetX = 0.0f,
      float EmojiOffsetY = 0.0f,
      int MoveStartFrame = 0,
      int MoveEndFrame = 0,
      int JumpMotionFrame = 0,
      int AppearFrame = 0,
      bool CanMove = false,
      bool CanFix = false,
      bool CanCrowdControl = false,
      bool CanBattleItemMove = false,
      bool IsAirUnit = false,
      long AirUnitHeight = 0,
      int TagsLength = 0,
      long SecretStoneItemId = 0,
      int SecretStoneItemAmount = 0,
      long CharacterPieceItemId = 0,
      int CharacterPieceItemAmount = 0,
      long CombineRecipeId = 0) {
    builder.StartTable(64);
    CharacterExcel.AddCombineRecipeId(builder, CombineRecipeId);
    CharacterExcel.AddCharacterPieceItemId(builder, CharacterPieceItemId);
    CharacterExcel.AddSecretStoneItemId(builder, SecretStoneItemId);
    CharacterExcel.AddAirUnitHeight(builder, AirUnitHeight);
    CharacterExcel.AddRandomEffectRadius(builder, RandomEffectRadius);
    CharacterExcel.AddBodyRadius(builder, BodyRadius);
    CharacterExcel.AddMainCombatStyleId(builder, MainCombatStyleId);
    CharacterExcel.AddExternalBTId(builder, ExternalBTId);
    CharacterExcel.AddCharacterAIId(builder, CharacterAIId);
    CharacterExcel.AddPersonalityId(builder, PersonalityId);
    CharacterExcel.AddCostumeGroupId(builder, CostumeGroupId);
    CharacterExcel.AddId(builder, Id);
    CharacterExcel.AddCharacterPieceItemAmount(builder, CharacterPieceItemAmount);
    CharacterExcel.AddSecretStoneItemAmount(builder, SecretStoneItemAmount);
    CharacterExcel.AddTagsLength(builder, TagsLength);
    CharacterExcel.AddAppearFrame(builder, AppearFrame);
    CharacterExcel.AddJumpMotionFrame(builder, JumpMotionFrame);
    CharacterExcel.AddMoveEndFrame(builder, MoveEndFrame);
    CharacterExcel.AddMoveStartFrame(builder, MoveStartFrame);
    CharacterExcel.AddEmojiOffsetY(builder, EmojiOffsetY);
    CharacterExcel.AddEmojiOffsetX(builder, EmojiOffsetX);
    CharacterExcel.AddHighlightFloaterHeight(builder, HighlightFloaterHeight);
    CharacterExcel.AddHpBarHeight(builder, HpBarHeight);
    CharacterExcel.AddWeaponLocalizeId(builder, WeaponLocalizeId);
    CharacterExcel.AddEquipmentSlotLength(builder, EquipmentSlotLength);
    CharacterExcel.AddFavorLevelupType(builder, FavorLevelupType);
    CharacterExcel.AddSpawnTemplateId(builder, SpawnTemplateId);
    CharacterExcel.AddScenarioCharacter(builder, ScenarioCharacterOffset);
    CharacterExcel.AddCombatStyleIndex(builder, CombatStyleIndex);
    CharacterExcel.AddSquadType(builder, SquadType);
    CharacterExcel.AddStatLevelUpType(builder, StatLevelUpType);
    CharacterExcel.AddMaxStarGrade(builder, MaxStarGrade);
    CharacterExcel.AddDefaultStarGrade(builder, DefaultStarGrade);
    CharacterExcel.AddClub(builder, Club);
    CharacterExcel.AddSchool(builder, School);
    CharacterExcel.AddAimIKType(builder, AimIKType);
    CharacterExcel.AddArmorType(builder, ArmorType);
    CharacterExcel.AddBulletType(builder, BulletType);
    CharacterExcel.AddTacticRange(builder, TacticRange);
    CharacterExcel.AddWeaponType(builder, WeaponType);
    CharacterExcel.AddTacticRole(builder, TacticRole);
    CharacterExcel.AddSubPartsCount(builder, SubPartsCount);
    CharacterExcel.AddTacticEntityType(builder, TacticEntityType);
    CharacterExcel.AddRarity(builder, Rarity);
    CharacterExcel.AddLocalizeEtcId(builder, LocalizeEtcId);
    CharacterExcel.AddCollectionVisibleEndDate(builder, CollectionVisibleEndDateOffset);
    CharacterExcel.AddCollectionVisibleStartDate(builder, CollectionVisibleStartDateOffset);
    CharacterExcel.AddReleaseDate(builder, ReleaseDateOffset);
    CharacterExcel.AddProductionStep(builder, ProductionStep);
    CharacterExcel.AddDevName(builder, DevNameOffset);
    CharacterExcel.AddIsAirUnit(builder, IsAirUnit);
    CharacterExcel.AddCanBattleItemMove(builder, CanBattleItemMove);
    CharacterExcel.AddCanCrowdControl(builder, CanCrowdControl);
    CharacterExcel.AddCanFix(builder, CanFix);
    CharacterExcel.AddCanMove(builder, CanMove);
    CharacterExcel.AddHPBarHide(builder, HPBarHide);
    CharacterExcel.AddDisplayEnemyInfo(builder, DisplayEnemyInfo);
    CharacterExcel.AddJumpable(builder, Jumpable);
    CharacterExcel.AddIsDummy(builder, IsDummy);
    CharacterExcel.AddCanSurvive(builder, CanSurvive);
    CharacterExcel.AddIsNPC(builder, IsNPC);
    CharacterExcel.AddIsPlayableCharacter(builder, IsPlayableCharacter);
    CharacterExcel.AddCollectionVisible(builder, CollectionVisible);
    CharacterExcel.AddIsPlayable(builder, IsPlayable);
    return CharacterExcel.EndCharacterExcel(builder);
  }

  public static void StartCharacterExcel(FlatBufferBuilder builder) { builder.StartTable(64); }
  public static void AddId(FlatBufferBuilder builder, long id) { builder.AddLong(0, id, 0); }
  public static void AddDevName(FlatBufferBuilder builder, StringOffset devNameOffset) { builder.AddOffset(1, devNameOffset.Value, 0); }
  public static void AddCostumeGroupId(FlatBufferBuilder builder, long costumeGroupId) { builder.AddLong(2, costumeGroupId, 0); }
  public static void AddIsPlayable(FlatBufferBuilder builder, bool isPlayable) { builder.AddBool(3, isPlayable, false); }
  public static void AddProductionStep(FlatBufferBuilder builder, Ivaldi.FlatBuffers.Common.ProductionStep productionStep) { builder.AddInt(4, (int)productionStep, 0); }
  public static void AddCollectionVisible(FlatBufferBuilder builder, bool collectionVisible) { builder.AddBool(5, collectionVisible, false); }
  public static void AddReleaseDate(FlatBufferBuilder builder, StringOffset releaseDateOffset) { builder.AddOffset(6, releaseDateOffset.Value, 0); }
  public static void AddCollectionVisibleStartDate(FlatBufferBuilder builder, StringOffset collectionVisibleStartDateOffset) { builder.AddOffset(7, collectionVisibleStartDateOffset.Value, 0); }
  public static void AddCollectionVisibleEndDate(FlatBufferBuilder builder, StringOffset collectionVisibleEndDateOffset) { builder.AddOffset(8, collectionVisibleEndDateOffset.Value, 0); }
  public static void AddIsPlayableCharacter(FlatBufferBuilder builder, bool isPlayableCharacter) { builder.AddBool(9, isPlayableCharacter, false); }
  public static void AddLocalizeEtcId(FlatBufferBuilder builder, uint localizeEtcId) { builder.AddUint(10, localizeEtcId, 0); }
  public static void AddRarity(FlatBufferBuilder builder, Ivaldi.FlatBuffers.CharacterExcel.Rarity rarity) { builder.AddInt(11, (int)rarity, 0); }
  public static void AddIsNPC(FlatBufferBuilder builder, bool isNPC) { builder.AddBool(12, isNPC, false); }
  public static void AddTacticEntityType(FlatBufferBuilder builder, Ivaldi.FlatBuffers.CharacterExcel.TacticEntityType tacticEntityType) { builder.AddInt(13, (int)tacticEntityType, 0); }
  public static void AddCanSurvive(FlatBufferBuilder builder, bool canSurvive) { builder.AddBool(14, canSurvive, false); }
  public static void AddIsDummy(FlatBufferBuilder builder, bool isDummy) { builder.AddBool(15, isDummy, false); }
  public static void AddSubPartsCount(FlatBufferBuilder builder, int subPartsCount) { builder.AddInt(16, subPartsCount, 0); }
  public static void AddTacticRole(FlatBufferBuilder builder, Ivaldi.FlatBuffers.CharacterExcel.TacticRole tacticRole) { builder.AddInt(17, (int)tacticRole, 0); }
  public static void AddWeaponType(FlatBufferBuilder builder, Ivaldi.FlatBuffers.CharacterExcel.WeaponType weaponType) { builder.AddInt(18, (int)weaponType, 0); }
  public static void AddTacticRange(FlatBufferBuilder builder, Ivaldi.FlatBuffers.CharacterExcel.TacticRange tacticRange) { builder.AddInt(19, (int)tacticRange, 0); }
  public static void AddBulletType(FlatBufferBuilder builder, Ivaldi.FlatBuffers.CharacterExcel.BulletType bulletType) { builder.AddInt(20, (int)bulletType, 0); }
  public static void AddArmorType(FlatBufferBuilder builder, Ivaldi.FlatBuffers.CharacterExcel.ArmorType armorType) { builder.AddInt(21, (int)armorType, 0); }
  public static void AddAimIKType(FlatBufferBuilder builder, Ivaldi.FlatBuffers.CharacterExcel.AimIKType aimIKType) { builder.AddInt(22, (int)aimIKType, 0); }
  public static void AddSchool(FlatBufferBuilder builder, Ivaldi.FlatBuffers.CharacterExcel.School school) { builder.AddInt(23, (int)school, 0); }
  public static void AddClub(FlatBufferBuilder builder, Ivaldi.FlatBuffers.CharacterExcel.Club club) { builder.AddInt(24, (int)club, 0); }
  public static void AddDefaultStarGrade(FlatBufferBuilder builder, int defaultStarGrade) { builder.AddInt(25, defaultStarGrade, 0); }
  public static void AddMaxStarGrade(FlatBufferBuilder builder, int maxStarGrade) { builder.AddInt(26, maxStarGrade, 0); }
  public static void AddStatLevelUpType(FlatBufferBuilder builder, Ivaldi.FlatBuffers.CharacterExcel.StatLevelUpType statLevelUpType) { builder.AddInt(27, (int)statLevelUpType, 0); }
  public static void AddSquadType(FlatBufferBuilder builder, Ivaldi.FlatBuffers.CharacterExcel.SquadType squadType) { builder.AddInt(28, (int)squadType, 0); }
  public static void AddJumpable(FlatBufferBuilder builder, bool jumpable) { builder.AddBool(29, jumpable, false); }
  public static void AddPersonalityId(FlatBufferBuilder builder, long personalityId) { builder.AddLong(30, personalityId, 0); }
  public static void AddCharacterAIId(FlatBufferBuilder builder, long characterAIId) { builder.AddLong(31, characterAIId, 0); }
  public static void AddExternalBTId(FlatBufferBuilder builder, long externalBTId) { builder.AddLong(32, externalBTId, 0); }
  public static void AddMainCombatStyleId(FlatBufferBuilder builder, long mainCombatStyleId) { builder.AddLong(33, mainCombatStyleId, 0); }
  public static void AddCombatStyleIndex(FlatBufferBuilder builder, int combatStyleIndex) { builder.AddInt(34, combatStyleIndex, 0); }
  public static void AddScenarioCharacter(FlatBufferBuilder builder, StringOffset scenarioCharacterOffset) { builder.AddOffset(35, scenarioCharacterOffset.Value, 0); }
  public static void AddSpawnTemplateId(FlatBufferBuilder builder, uint spawnTemplateId) { builder.AddUint(36, spawnTemplateId, 0); }
  public static void AddFavorLevelupType(FlatBufferBuilder builder, int favorLevelupType) { builder.AddInt(37, favorLevelupType, 0); }
  public static void AddEquipmentSlotLength(FlatBufferBuilder builder, int equipmentSlotLength) { builder.AddInt(38, equipmentSlotLength, 0); }
  public static void AddWeaponLocalizeId(FlatBufferBuilder builder, uint weaponLocalizeId) { builder.AddUint(39, weaponLocalizeId, 0); }
  public static void AddDisplayEnemyInfo(FlatBufferBuilder builder, bool displayEnemyInfo) { builder.AddBool(40, displayEnemyInfo, false); }
  public static void AddBodyRadius(FlatBufferBuilder builder, long bodyRadius) { builder.AddLong(41, bodyRadius, 0); }
  public static void AddRandomEffectRadius(FlatBufferBuilder builder, long randomEffectRadius) { builder.AddLong(42, randomEffectRadius, 0); }
  public static void AddHPBarHide(FlatBufferBuilder builder, bool hPBarHide) { builder.AddBool(43, hPBarHide, false); }
  public static void AddHpBarHeight(FlatBufferBuilder builder, float hpBarHeight) { builder.AddFloat(44, hpBarHeight, 0.0f); }
  public static void AddHighlightFloaterHeight(FlatBufferBuilder builder, float highlightFloaterHeight) { builder.AddFloat(45, highlightFloaterHeight, 0.0f); }
  public static void AddEmojiOffsetX(FlatBufferBuilder builder, float emojiOffsetX) { builder.AddFloat(46, emojiOffsetX, 0.0f); }
  public static void AddEmojiOffsetY(FlatBufferBuilder builder, float emojiOffsetY) { builder.AddFloat(47, emojiOffsetY, 0.0f); }
  public static void AddMoveStartFrame(FlatBufferBuilder builder, int moveStartFrame) { builder.AddInt(48, moveStartFrame, 0); }
  public static void AddMoveEndFrame(FlatBufferBuilder builder, int moveEndFrame) { builder.AddInt(49, moveEndFrame, 0); }
  public static void AddJumpMotionFrame(FlatBufferBuilder builder, int jumpMotionFrame) { builder.AddInt(50, jumpMotionFrame, 0); }
  public static void AddAppearFrame(FlatBufferBuilder builder, int appearFrame) { builder.AddInt(51, appearFrame, 0); }
  public static void AddCanMove(FlatBufferBuilder builder, bool canMove) { builder.AddBool(52, canMove, false); }
  public static void AddCanFix(FlatBufferBuilder builder, bool canFix) { builder.AddBool(53, canFix, false); }
  public static void AddCanCrowdControl(FlatBufferBuilder builder, bool canCrowdControl) { builder.AddBool(54, canCrowdControl, false); }
  public static void AddCanBattleItemMove(FlatBufferBuilder builder, bool canBattleItemMove) { builder.AddBool(55, canBattleItemMove, false); }
  public static void AddIsAirUnit(FlatBufferBuilder builder, bool isAirUnit) { builder.AddBool(56, isAirUnit, false); }
  public static void AddAirUnitHeight(FlatBufferBuilder builder, long airUnitHeight) { builder.AddLong(57, airUnitHeight, 0); }
  public static void AddTagsLength(FlatBufferBuilder builder, int tagsLength) { builder.AddInt(58, tagsLength, 0); }
  public static void AddSecretStoneItemId(FlatBufferBuilder builder, long secretStoneItemId) { builder.AddLong(59, secretStoneItemId, 0); }
  public static void AddSecretStoneItemAmount(FlatBufferBuilder builder, int secretStoneItemAmount) { builder.AddInt(60, secretStoneItemAmount, 0); }
  public static void AddCharacterPieceItemId(FlatBufferBuilder builder, long characterPieceItemId) { builder.AddLong(61, characterPieceItemId, 0); }
  public static void AddCharacterPieceItemAmount(FlatBufferBuilder builder, int characterPieceItemAmount) { builder.AddInt(62, characterPieceItemAmount, 0); }
  public static void AddCombineRecipeId(FlatBufferBuilder builder, long combineRecipeId) { builder.AddLong(63, combineRecipeId, 0); }
  public static Offset<Ivaldi.FlatBuffers.CharacterExcel.CharacterExcel> EndCharacterExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Ivaldi.FlatBuffers.CharacterExcel.CharacterExcel>(o);
  }
}


static public class CharacterExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 8 /*long*/, 8, false)
      && verifier.VerifyString(tablePos, 6 /*DevName*/, false)
      && verifier.VerifyField(tablePos, 8 /*CostumeGroupId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 10 /*IsPlayable*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 12 /*ProductionStep*/, 4 /*Ivaldi.FlatBuffers.Common.ProductionStep*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*CollectionVisible*/, 1 /*bool*/, 1, false)
      && verifier.VerifyString(tablePos, 16 /*ReleaseDate*/, false)
      && verifier.VerifyString(tablePos, 18 /*CollectionVisibleStartDate*/, false)
      && verifier.VerifyString(tablePos, 20 /*CollectionVisibleEndDate*/, false)
      && verifier.VerifyField(tablePos, 22 /*IsPlayableCharacter*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 24 /*LocalizeEtcId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 26 /*Rarity*/, 4 /*Ivaldi.FlatBuffers.CharacterExcel.Rarity*/, 4, false)
      && verifier.VerifyField(tablePos, 28 /*IsNPC*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 30 /*TacticEntityType*/, 4 /*Ivaldi.FlatBuffers.CharacterExcel.TacticEntityType*/, 4, false)
      && verifier.VerifyField(tablePos, 32 /*CanSurvive*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 34 /*IsDummy*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 36 /*SubPartsCount*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 38 /*TacticRole*/, 4 /*Ivaldi.FlatBuffers.CharacterExcel.TacticRole*/, 4, false)
      && verifier.VerifyField(tablePos, 40 /*WeaponType*/, 4 /*Ivaldi.FlatBuffers.CharacterExcel.WeaponType*/, 4, false)
      && verifier.VerifyField(tablePos, 42 /*TacticRange*/, 4 /*Ivaldi.FlatBuffers.CharacterExcel.TacticRange*/, 4, false)
      && verifier.VerifyField(tablePos, 44 /*BulletType*/, 4 /*Ivaldi.FlatBuffers.CharacterExcel.BulletType*/, 4, false)
      && verifier.VerifyField(tablePos, 46 /*ArmorType*/, 4 /*Ivaldi.FlatBuffers.CharacterExcel.ArmorType*/, 4, false)
      && verifier.VerifyField(tablePos, 48 /*AimIKType*/, 4 /*Ivaldi.FlatBuffers.CharacterExcel.AimIKType*/, 4, false)
      && verifier.VerifyField(tablePos, 50 /*School*/, 4 /*Ivaldi.FlatBuffers.CharacterExcel.School*/, 4, false)
      && verifier.VerifyField(tablePos, 52 /*Club*/, 4 /*Ivaldi.FlatBuffers.CharacterExcel.Club*/, 4, false)
      && verifier.VerifyField(tablePos, 54 /*DefaultStarGrade*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 56 /*MaxStarGrade*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 58 /*StatLevelUpType*/, 4 /*Ivaldi.FlatBuffers.CharacterExcel.StatLevelUpType*/, 4, false)
      && verifier.VerifyField(tablePos, 60 /*SquadType*/, 4 /*Ivaldi.FlatBuffers.CharacterExcel.SquadType*/, 4, false)
      && verifier.VerifyField(tablePos, 62 /*Jumpable*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 64 /*PersonalityId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 66 /*CharacterAIId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 68 /*ExternalBTId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 70 /*MainCombatStyleId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 72 /*CombatStyleIndex*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 74 /*ScenarioCharacter*/, false)
      && verifier.VerifyField(tablePos, 76 /*SpawnTemplateId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 78 /*FavorLevelupType*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 80 /*EquipmentSlotLength*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 82 /*WeaponLocalizeId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 84 /*DisplayEnemyInfo*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 86 /*BodyRadius*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 88 /*RandomEffectRadius*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 90 /*HPBarHide*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 92 /*HpBarHeight*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 94 /*HighlightFloaterHeight*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 96 /*EmojiOffsetX*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 98 /*EmojiOffsetY*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 100 /*MoveStartFrame*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 102 /*MoveEndFrame*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 104 /*JumpMotionFrame*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 106 /*AppearFrame*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 108 /*CanMove*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 110 /*CanFix*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 112 /*CanCrowdControl*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 114 /*CanBattleItemMove*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 116 /*IsAirUnit*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 118 /*AirUnitHeight*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 120 /*TagsLength*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 122 /*SecretStoneItemId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 124 /*SecretStoneItemAmount*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 126 /*CharacterPieceItemId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 128 /*CharacterPieceItemAmount*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 130 /*CombineRecipeId*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
