// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Ivaldi.FlatBuffers.CharacterExcel
{

public enum SquadType : int
{
  None = 0,
  Main = 1,
  Support = 2,
  TSS = 3,
};


}
