// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Ivaldi.FlatBuffers.CharacterExcel
{

public enum StatLevelUpType : int
{
  Standard = 0,
  Premature = 1,
  LateBloom = 2,
  Obstacle = 3,
  TimeAttack = 4,
};


}
