// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Ivaldi.FlatBuffers.ScenarioCharacterNameExcel
{

public enum DialogType : int
{
  Talk = 0,
  Think = 1,
  UITalk = 2,
};


}
