// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Ivaldi.FlatBuffers.ScenarioCharacterNameExcel
{

public enum ScenarioCharacterShapes : int
{
  None = 0,
  Signal = 1,
  BlackSilhouette = 2,
  Closeup = 4,
  Highlight = 8,
  WhiteSilhouette = 16,
};


}
