// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Ivaldi.FlatBuffers.MemoryLobbyExcel
{

public enum MemoryLobbyCategory : int
{
  None = 0,
  UILobbySpecial = 1,
  UILobbySpecial2 = 2,
};


}
